# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
domain: nilaos.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://nilaos.github.io  # the base hostname and protocol for your site, e.g. http://example.com
# baseurl: /      # place folder name if the site is served in a subfolder
#twitter_username: 
github_username:  Nilaos
repository: Nilaos/nilaos.github.io


markdown: GFM

header_pages:
  - about.md
  - index.html

# Build settings
theme: minima
remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  # - jekyll-archives

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layout: archive
#   permalinks: '/:year/:month/:day/:title/' # or '/:category/:title/'?

# Pagination
paginate: 8
paginate_path: "/page:num/"

# SEO
title_separator: " | "
seo:
  name: Nicholas Sims
  social:
    - type: github
      username: nilaos

# Sitemap
sitemap:
  exclude:
    - /atom
    - /feed.xml
    - /README.md

# Other
markdown: kramdown

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
