name: Publish gh pages

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    # configure the environment
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3.0.0
      with:
        node-version: '16'
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
        target: wasm32-unknown-unknown
    - name: trunk-action
      uses: jetli/trunk-action@v0.2.0

    # build css and rust
    - name: run trunk
      working-directory: ./crates/website/
      run: trunk build --release

    # deploy for github.io
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./crates/website/dist
        force_orphan: true